"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../context";
import { MantineProvider } from "@mantine/core";
import { GameHomeConfix } from "./context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Civics Final Online Board game",
  description: "Generated by create next app",
};

function LocalProviders({ children }: { children: React.ReactNode }) {
  return (
    <>
      <GameHomeConfix>{children}</GameHomeConfix>
    </>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider
          theme={{ colorScheme: "dark" }}
          withGlobalStyles
          withNormalizeCSS
        >
          <Providers>
            <LocalProviders>{children}</LocalProviders>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
